# Generated by Django 3.1.7 on 2021-09-03 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RestApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsertoken',
            name='token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='browsertoken',
            unique_together={('token', 'user')},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('isSeen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
