# Generated by Django 3.1.7 on 2021-09-03 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RestApi', '0002_auto_20210903_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsertoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='browsertoken',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='browsertoken',
            name='id',
        ),
    ]
